In [1]:
from tensorflow.keras.preprocessing.text import one_hot


In [2]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
vocab_size=10000

one_hot_repr=[one_hot(word,vocab_size)for word in sent]

In [4]:
one_hot_repr

[[342, 2493, 1582, 1701],
 [342, 2493, 1582, 6074],
 [342, 546, 1582, 5947],
 [9549, 5146, 3778, 4049, 6053],
 [9549, 5146, 3778, 4049, 3133],
 [6316, 342, 1999, 1582, 3337],
 [705, 1928, 2016, 4049]]

In [7]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [9]:
import numpy as np

In [10]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)

In [11]:
print(embedded_docs)

[[   0    0    0    0  342 2493 1582 1701]
 [   0    0    0    0  342 2493 1582 6074]
 [   0    0    0    0  342  546 1582 5947]
 [   0    0    0 9549 5146 3778 4049 6053]
 [   0    0    0 9549 5146 3778 4049 3133]
 [   0    0    0 6316  342 1999 1582 3337]
 [   0    0    0    0  705 1928 2016 4049]]


In [12]:
dim=10
model=Sequential()
model.add(Embedding(vocab_size,dim,input_length=sent_length))
model.compile('adam','mse')

d:\gen ai + huggingface langchain\10- Ann project implementation\venv\Lib\site-packages\keras\src\layers\core\embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [13]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [14]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 3s 3s/step


array([[[-0.00725372, -0.04354075, -0.03859257,  0.03703089,
          0.00738177,  0.0043125 , -0.00782843, -0.04205843,
          0.04379556,  0.00333292],
        [-0.00725372, -0.04354075, -0.03859257,  0.03703089,
          0.00738177,  0.0043125 , -0.00782843, -0.04205843,
          0.04379556,  0.00333292],
        [-0.00725372, -0.04354075, -0.03859257,  0.03703089,
          0.00738177,  0.0043125 , -0.00782843, -0.04205843,
          0.04379556,  0.00333292],
        [-0.00725372, -0.04354075, -0.03859257,  0.03703089,
          0.00738177,  0.0043125 , -0.00782843, -0.04205843,
          0.04379556,  0.00333292],
        [ 0.01455675, -0.04992661,  0.03157126, -0.04375033,
         -0.04129425, -0.03244855, -0.04373084, -0.00634875,
         -0.00397612, -0.01620687],
        [-0.04060157, -0.02035655, -0.04534568,  0.02730396,
         -0.04733915,  0.0221895 ,  0.00421798, -0.04237663,
         -0.03767006,  0.00253472],
        [ 0.0228837 ,  0.0058522 , -0.00652994,  0.0

In [16]:
print(embedded_docs[0])
print(model.predict(embedded_docs)[0])

[   0    0    0    0  342 2493 1582 1701]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 73ms/step
[[-0.00725372 -0.04354075 -0.03859257  0.03703089  0.00738177  0.0043125
  -0.00782843 -0.04205843  0.04379556  0.00333292]
 [-0.00725372 -0.04354075 -0.03859257  0.03703089  0.00738177  0.0043125
  -0.00782843 -0.04205843  0.04379556  0.00333292]
 [-0.00725372 -0.04354075 -0.03859257  0.03703089  0.00738177  0.0043125
  -0.00782843 -0.04205843  0.04379556  0.00333292]
 [-0.00725372 -0.04354075 -0.03859257  0.03703089  0.00738177  0.0043125
  -0.00782843 -0.04205843  0.04379556  0.00333292]
 [ 0.01455675 -0.04992661  0.03157126 -0.04375033 -0.04129425 -0.03244855
  -0.04373084 -0.00634875 -0.00397612 -0.01620687]
 [-0.04060157 -0.02035655 -0.04534568  0.02730396 -0.04733915  0.0221895
   0.00421798 -0.04237663 -0.03767006  0.00253472]
 [ 0.0228837   0.0058522  -0.00652994  0.01799381  0.00548441 -0.04380981
  -0.04425535  0.0302056  -0.02970113 -0.01985536]
 [-0.00251547  0.01295724  0.01896821 -0.02600167 